vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.g.mapleader = " "

vim.cmd("inoremap <A-3> #")
vim.cmd("inoremap ' ''<Esc>i")
vim.cmd("inoremap { {}<Esc>i")
vim.cmd("inoremap [ []<Esc>i")
vim.cmd("inoremap ( ()<Esc>i")
vim.cmd("inoremap ` ``<Esc>i")
vim.cmd('inoremap " ""<Esc>i')
vim.cmd("nnoremap <leader>hl :noh<CR>")
